
from PyQt5 import QtCore, QtGui, QtWidgets
from process import handle

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1112, 831)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setAcceptDrops(True)
        self.tabWidget.setToolTipDuration(6)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1068, 747))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(660, 10, 401, 381))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setGeometry(QtCore.QRect(70, 70, 21, 16))
        self.label_46.setObjectName("label_46")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 70, 51, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 120, 51, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_57 = QtWidgets.QLabel(self.groupBox_2)
        self.label_57.setGeometry(QtCore.QRect(70, 120, 21, 16))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setGeometry(QtCore.QRect(70, 170, 21, 16))
        self.label_58.setObjectName("label_58")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 170, 51, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 220, 51, 20))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_59 = QtWidgets.QLabel(self.groupBox_2)
        self.label_59.setGeometry(QtCore.QRect(70, 220, 21, 16))
        self.label_59.setObjectName("label_59")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_6.setGeometry(QtCore.QRect(20, 270, 51, 20))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_60 = QtWidgets.QLabel(self.groupBox_2)
        self.label_60.setGeometry(QtCore.QRect(70, 270, 21, 16))
        self.label_60.setObjectName("label_60")
        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_7.setGeometry(QtCore.QRect(20, 310, 51, 20))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_61 = QtWidgets.QLabel(self.groupBox_2)
        self.label_61.setGeometry(QtCore.QRect(70, 310, 21, 16))
        self.label_61.setObjectName("label_61")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(11, 20, 16, 16))
        self.label_28.setObjectName("label_28")
        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_1.setGeometry(QtCore.QRect(20, 20, 51, 20))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.expression_lineEdit_1_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_1_1.setGeometry(QtCore.QRect(100, 20, 42, 20))
        self.expression_lineEdit_1_1.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_1_1.setObjectName("expression_lineEdit_1_1")
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(70, 20, 21, 16))
        self.label_45.setObjectName("label_45")
        self.expression_lineEdit_1_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_1_2.setGeometry(QtCore.QRect(190, 20, 42, 20))
        self.expression_lineEdit_1_2.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_1_2.setObjectName("expression_lineEdit_1_2")
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(150, 20, 41, 16))
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(230, 20, 41, 16))
        self.label_32.setObjectName("label_32")
        self.expression_lineEdit_1_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_1_3.setGeometry(QtCore.QRect(270, 20, 42, 20))
        self.expression_lineEdit_1_3.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_1_3.setObjectName("expression_lineEdit_1_3")
        self.expression_lineEdit_1_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_1_4.setGeometry(QtCore.QRect(350, 20, 42, 20))
        self.expression_lineEdit_1_4.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_1_4.setObjectName("expression_lineEdit_1_4")
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(320, 20, 21, 16))
        self.label_44.setObjectName("label_44")
        self.expression_lineEdit_2_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_2_1.setGeometry(QtCore.QRect(100, 70, 42, 20))
        self.expression_lineEdit_2_1.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_2_1.setObjectName("expression_lineEdit_2_1")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(11, 70, 16, 16))
        self.label_30.setObjectName("label_30")
        self.expression_lineEdit_2_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_2_2.setGeometry(QtCore.QRect(190, 70, 42, 20))
        self.expression_lineEdit_2_2.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_2_2.setObjectName("expression_lineEdit_2_2")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(11, 122, 16, 16))
        self.label_34.setObjectName("label_34")
        self.expression_lineEdit_3_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_3_1.setGeometry(QtCore.QRect(100, 120, 42, 20))
        self.expression_lineEdit_3_1.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_3_1.setObjectName("expression_lineEdit_3_1")
        self.expression_lineEdit_3_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_3_2.setGeometry(QtCore.QRect(190, 120, 42, 20))
        self.expression_lineEdit_3_2.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_3_2.setObjectName("expression_lineEdit_3_2")
        self.expression_lineEdit_3_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_3_3.setGeometry(QtCore.QRect(270, 120, 42, 20))
        self.expression_lineEdit_3_3.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_3_3.setObjectName("expression_lineEdit_3_3")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(11, 171, 16, 16))
        self.label_37.setObjectName("label_37")
        self.expression_lineEdit_4_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_4_1.setGeometry(QtCore.QRect(100, 170, 42, 20))
        self.expression_lineEdit_4_1.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_4_1.setObjectName("expression_lineEdit_4_1")
        self.expression_lineEdit_4_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_4_2.setGeometry(QtCore.QRect(190, 170, 42, 20))
        self.expression_lineEdit_4_2.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_4_2.setObjectName("expression_lineEdit_4_2")
        self.expression_lineEdit_5_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_5_1.setGeometry(QtCore.QRect(100, 220, 42, 20))
        self.expression_lineEdit_5_1.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_5_1.setObjectName("expression_lineEdit_5_1")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(11, 221, 16, 16))
        self.label_39.setObjectName("label_39")
        self.expression_lineEdit_5_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_5_2.setGeometry(QtCore.QRect(190, 220, 42, 20))
        self.expression_lineEdit_5_2.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_5_2.setObjectName("expression_lineEdit_5_2")
        self.expression_lineEdit_5_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_5_3.setGeometry(QtCore.QRect(270, 220, 42, 20))
        self.expression_lineEdit_5_3.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_5_3.setObjectName("expression_lineEdit_5_3")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(11, 270, 16, 16))
        self.label_16.setObjectName("label_16")
        self.expression_lineEdit_6_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_6_1.setGeometry(QtCore.QRect(100, 270, 42, 20))
        self.expression_lineEdit_6_1.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_6_1.setObjectName("expression_lineEdit_6_1")
        self.expression_lineEdit_6_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_6_2.setGeometry(QtCore.QRect(190, 270, 42, 20))
        self.expression_lineEdit_6_2.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_6_2.setObjectName("expression_lineEdit_6_2")
        self.expression_lineEdit_7_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_7_1.setGeometry(QtCore.QRect(100, 310, 42, 20))
        self.expression_lineEdit_7_1.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_7_1.setObjectName("expression_lineEdit_7_1")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(11, 310, 16, 16))
        self.label_18.setObjectName("label_18")
        self.expression_lineEdit_7_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_7_2.setGeometry(QtCore.QRect(190, 310, 42, 21))
        self.expression_lineEdit_7_2.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_7_2.setObjectName("expression_lineEdit_7_2")
        self.expression_lineEdit_7_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_7_3.setGeometry(QtCore.QRect(270, 310, 42, 20))
        self.expression_lineEdit_7_3.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_7_3.setObjectName("expression_lineEdit_7_3")
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(230, 70, 41, 16))
        self.label_47.setObjectName("label_47")
        self.expression_lineEdit_2_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_2_3.setGeometry(QtCore.QRect(270, 70, 42, 20))
        self.expression_lineEdit_2_3.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_2_3.setObjectName("expression_lineEdit_2_3")
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        self.label_48.setGeometry(QtCore.QRect(320, 70, 21, 16))
        self.label_48.setObjectName("label_48")
        self.expression_lineEdit_2_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_2_4.setGeometry(QtCore.QRect(350, 70, 42, 20))
        self.expression_lineEdit_2_4.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_2_4.setObjectName("expression_lineEdit_2_4")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(150, 70, 41, 16))
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(150, 120, 41, 16))
        self.label_33.setObjectName("label_33")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(140, 170, 41, 16))
        self.label_35.setObjectName("label_35")
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setGeometry(QtCore.QRect(150, 220, 41, 16))
        self.label_43.setObjectName("label_43")
        self.label_49 = QtWidgets.QLabel(self.groupBox_2)
        self.label_49.setGeometry(QtCore.QRect(150, 270, 41, 16))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_2)
        self.label_50.setGeometry(QtCore.QRect(143, 310, 41, 16))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.groupBox_2)
        self.label_51.setGeometry(QtCore.QRect(230, 120, 41, 16))
        self.label_51.setObjectName("label_51")
        self.label_63 = QtWidgets.QLabel(self.groupBox_2)
        self.label_63.setGeometry(QtCore.QRect(230, 170, 41, 16))
        self.label_63.setObjectName("label_63")
        self.label_64 = QtWidgets.QLabel(self.groupBox_2)
        self.label_64.setGeometry(QtCore.QRect(230, 220, 41, 16))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.groupBox_2)
        self.label_65.setGeometry(QtCore.QRect(235, 270, 41, 16))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_2)
        self.label_66.setGeometry(QtCore.QRect(230, 310, 41, 16))
        self.label_66.setObjectName("label_66")
        self.expression_lineEdit_4_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_4_3.setGeometry(QtCore.QRect(270, 170, 42, 20))
        self.expression_lineEdit_4_3.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_4_3.setObjectName("expression_lineEdit_4_3")
        self.expression_lineEdit_6_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_6_3.setGeometry(QtCore.QRect(270, 270, 42, 20))
        self.expression_lineEdit_6_3.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_6_3.setObjectName("expression_lineEdit_6_3")
        self.expression_lineEdit_3_6 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_3_6.setGeometry(QtCore.QRect(350, 120, 42, 20))
        self.expression_lineEdit_3_6.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_3_6.setObjectName("expression_lineEdit_3_6")
        self.label_67 = QtWidgets.QLabel(self.groupBox_2)
        self.label_67.setGeometry(QtCore.QRect(320, 120, 21, 16))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_2)
        self.label_68.setGeometry(QtCore.QRect(320, 170, 21, 16))
        self.label_68.setObjectName("label_68")
        self.expression_lineEdit_4_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_4_4.setGeometry(QtCore.QRect(350, 170, 42, 20))
        self.expression_lineEdit_4_4.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_4_4.setObjectName("expression_lineEdit_4_4")
        self.label_69 = QtWidgets.QLabel(self.groupBox_2)
        self.label_69.setGeometry(QtCore.QRect(320, 220, 21, 16))
        self.label_69.setObjectName("label_69")
        self.expression_lineEdit_5_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_5_4.setGeometry(QtCore.QRect(350, 220, 42, 20))
        self.expression_lineEdit_5_4.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_5_4.setObjectName("expression_lineEdit_5_4")
        self.label_70 = QtWidgets.QLabel(self.groupBox_2)
        self.label_70.setGeometry(QtCore.QRect(320, 270, 21, 16))
        self.label_70.setObjectName("label_70")
        self.expression_lineEdit_6_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_6_4.setGeometry(QtCore.QRect(350, 270, 42, 20))
        self.expression_lineEdit_6_4.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_6_4.setObjectName("expression_lineEdit_6_4")
        self.label_71 = QtWidgets.QLabel(self.groupBox_2)
        self.label_71.setGeometry(QtCore.QRect(320, 310, 21, 16))
        self.label_71.setObjectName("label_71")
        self.expression_lineEdit_7_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_7_4.setGeometry(QtCore.QRect(350, 310, 42, 20))
        self.expression_lineEdit_7_4.setStyleSheet("min-width:40px;\n"
"max-width:40px;\n"
"width:40px")
        self.expression_lineEdit_7_4.setObjectName("expression_lineEdit_7_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 380, 401, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setGeometry(QtCore.QRect(90, 30, 49, 16))
        self.label_42.setObjectName("label_42")
        self.expression_lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_3)
        self.expression_lineEdit_41.setGeometry(QtCore.QRect(150, 30, 113, 22))
        self.expression_lineEdit_41.setAlignment(QtCore.Qt.AlignCenter)
        self.expression_lineEdit_41.setObjectName("expression_lineEdit_41")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(150, 70, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 120, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 170, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(150, 220, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 651, 741))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("max-width: 1000px")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(1002, 710))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.scrollArea_2.setFont(font)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 612, 686))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(1000, 794))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 2)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 14, 0, 1, 2)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 10, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 9, 0, 1, 3)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 3)
        self.label_52 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 8, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 11, 0, 1, 1)
        self.begin_expression_lineEdit_15 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_15.setFont(font)
        self.begin_expression_lineEdit_15.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_15.setObjectName("begin_expression_lineEdit_15")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_15, 14, 3, 1, 1)
        self.begin_expression_lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_11.setFont(font)
        self.begin_expression_lineEdit_11.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_11.setObjectName("begin_expression_lineEdit_11")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_11, 10, 3, 1, 1)
        self.begin_expression_lineEdit_14 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_14.setFont(font)
        self.begin_expression_lineEdit_14.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_14.setObjectName("begin_expression_lineEdit_14")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_14, 13, 3, 1, 1)
        self.begin_expression_lineEdit_12 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_12.setFont(font)
        self.begin_expression_lineEdit_12.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_12.setMaxLength(32773)
        self.begin_expression_lineEdit_12.setObjectName("begin_expression_lineEdit_12")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_12, 11, 3, 1, 1)
        self.begin_expression_lineEdit_13 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_13.setFont(font)
        self.begin_expression_lineEdit_13.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_13.setObjectName("begin_expression_lineEdit_13")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_13, 12, 3, 1, 1)
        self.begin_expression_lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_7.setFont(font)
        self.begin_expression_lineEdit_7.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_7.setObjectName("begin_expression_lineEdit_7")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_7, 6, 3, 1, 1)
        self.begin_expression_lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_10.setFont(font)
        self.begin_expression_lineEdit_10.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_10.setObjectName("begin_expression_lineEdit_10")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_10, 9, 3, 1, 1)
        self.begin_expression_lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_9.setFont(font)
        self.begin_expression_lineEdit_9.setStyleSheet("min-width:50px; width: 50px")
        self.begin_expression_lineEdit_9.setObjectName("begin_expression_lineEdit_9")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_9, 8, 3, 1, 1)
        self.begin_expression_lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_8.setFont(font)
        self.begin_expression_lineEdit_8.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_8.setObjectName("begin_expression_lineEdit_8")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_8, 7, 3, 1, 1)
        self.begin_expression_lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_6.setFont(font)
        self.begin_expression_lineEdit_6.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_6.setObjectName("begin_expression_lineEdit_6")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_6, 5, 3, 1, 1)
        self.begin_expression_lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_3.setFont(font)
        self.begin_expression_lineEdit_3.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_3.setObjectName("begin_expression_lineEdit_3")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_3, 2, 3, 1, 1)
        self.begin_expression_lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_5.setFont(font)
        self.begin_expression_lineEdit_5.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_5.setObjectName("begin_expression_lineEdit_5")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_5, 4, 3, 1, 1)
        self.begin_expression_lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_4.setFont(font)
        self.begin_expression_lineEdit_4.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_4.setObjectName("begin_expression_lineEdit_4")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_4, 3, 3, 1, 1)
        self.begin_expression_lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_2.setFont(font)
        self.begin_expression_lineEdit_2.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_2.setObjectName("begin_expression_lineEdit_2")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_2, 1, 3, 1, 1)
        self.begin_expression_lineEdit_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_expression_lineEdit_1.setFont(font)
        self.begin_expression_lineEdit_1.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_1.setObjectName("begin_expression_lineEdit_1")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_1, 0, 3, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("max-height : 800px;\n"
"max-width:1000px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../../.designer/Изображения/testImage.jpeg"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setIndent(-3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1051, 2642))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_55.setStyleSheet("max-height : 700px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.gridLayout_5.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_54.setMaximumSize(QtCore.QSize(700, 520))
        self.label_54.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_54.setStyleSheet("max-height : 700px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_54.setText("")
        self.label_54.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_54.setScaledContents(True)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setIndent(-3)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 1, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_53.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_53.setStyleSheet("max-height : 700px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_53.setScaledContents(True)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setIndent(-3)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_38.setMaximumSize(QtCore.QSize(700, 520))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_38.setStyleSheet("max-height : 700px;\n"
                                    "max-width:900px;\n"
                                    "margin-top: 10px;\n"
                                    "margin-bottom: 10px;")
        self.gridLayout_5.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_62.setMaximumSize(QtCore.QSize(700, 520))
        self.label_62.setStyleSheet("max-height : 700px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.gridLayout_5.addWidget(self.label_62, 4, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setEnabled(True)
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_56 = QtWidgets.QLabel(self.tab_4)
        self.label_56.setStyleSheet("max-height : 700px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("../../.designer/Изображения/testImage.jpeg"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_8.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.addItems()
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_3.setCurrentIndex(2)
        self.comboBox_4.setCurrentIndex(2)
        self.comboBox_5.setCurrentIndex(3)
        self.comboBox_6.setCurrentIndex(4)
        self.comboBox_7.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        handle(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "Уравнения"))
        self.label_46.setText(_translate("Dialog", "(x)="))
        self.comboBox_2.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "9"))
        self.comboBox_2.setItemText(9, _translate("Dialog", "10"))
        self.comboBox_2.setItemText(10, _translate("Dialog", "11"))
        self.comboBox_2.setItemText(11, _translate("Dialog", "12"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "8"))
        self.label_57.setText(_translate("Dialog", "(x)="))
        self.label_58.setText(_translate("Dialog", "(x)="))
        self.comboBox_4.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_4.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_4.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_5.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_5.setItemText(7, _translate("Dialog", "8"))
        self.label_59.setText(_translate("Dialog", "(x)="))
        self.comboBox_6.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_6.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_6.setItemText(7, _translate("Dialog", "8"))
        self.label_60.setText(_translate("Dialog", "(x)="))
        self.comboBox_7.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_7.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_7.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_7.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_7.setItemText(7, _translate("Dialog", "8"))
        self.label_61.setText(_translate("Dialog", "(x)="))
        self.label_28.setText(_translate("Dialog", "F"))
        self.comboBox_1.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_1.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_1.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_1.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_1.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_1.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_1.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_1.setItemText(7, _translate("Dialog", "8"))
        self.expression_lineEdit_1_1.setText(_translate("Dialog", "1"))
        self.label_45.setText(_translate("Dialog", "(x)="))
        self.expression_lineEdit_1_2.setText(_translate("Dialog", "1"))
        self.label_29.setText(_translate("Dialog", "*x^3+"))
        self.label_32.setText(_translate("Dialog", "*x^2+"))
        self.expression_lineEdit_1_3.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_1_4.setText(_translate("Dialog", "1"))
        self.label_44.setText(_translate("Dialog", "*x+"))
        self.expression_lineEdit_2_1.setText(_translate("Dialog", "1"))
        self.label_30.setText(_translate("Dialog", "F"))
        self.expression_lineEdit_2_2.setText(_translate("Dialog", "1"))
        self.label_34.setText(_translate("Dialog", "F"))
        self.expression_lineEdit_3_1.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_3_2.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_3_3.setText(_translate("Dialog", "1"))
        self.label_37.setText(_translate("Dialog", "F"))
        self.expression_lineEdit_4_1.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_4_2.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_5_1.setText(_translate("Dialog", "1"))
        self.label_39.setText(_translate("Dialog", "F"))
        self.expression_lineEdit_5_2.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_5_3.setText(_translate("Dialog", "1"))
        self.label_16.setText(_translate("Dialog", "F "))
        self.expression_lineEdit_6_1.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_6_2.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_7_1.setText(_translate("Dialog", "1"))
        self.label_18.setText(_translate("Dialog", "F"))
        self.expression_lineEdit_7_2.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_7_3.setText(_translate("Dialog", "1"))
        self.label_47.setText(_translate("Dialog", "*x^2+"))
        self.expression_lineEdit_2_3.setText(_translate("Dialog", "1"))
        self.label_48.setText(_translate("Dialog", "*x+"))
        self.expression_lineEdit_2_4.setText(_translate("Dialog", "1"))
        self.label_31.setText(_translate("Dialog", "*x^3+"))
        self.label_33.setText(_translate("Dialog", "*x^3+"))
        self.label_35.setText(_translate("Dialog", "*x^3+"))
        self.label_43.setText(_translate("Dialog", "*x^3+"))
        self.label_49.setText(_translate("Dialog", "*x^3+"))
        self.label_50.setText(_translate("Dialog", "*x^3+"))
        self.label_51.setText(_translate("Dialog", "*x^2+"))
        self.label_63.setText(_translate("Dialog", "*x^2+"))
        self.label_64.setText(_translate("Dialog", "*x^2+"))
        self.label_65.setText(_translate("Dialog", "*x^2+"))
        self.label_66.setText(_translate("Dialog", "*x^2+"))
        self.expression_lineEdit_4_3.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_6_3.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_3_6.setText(_translate("Dialog", "1"))
        self.label_67.setText(_translate("Dialog", "*x+"))
        self.label_68.setText(_translate("Dialog", "*x+"))
        self.expression_lineEdit_4_4.setText(_translate("Dialog", "1"))
        self.label_69.setText(_translate("Dialog", "*x+"))
        self.expression_lineEdit_5_4.setText(_translate("Dialog", "1"))
        self.label_70.setText(_translate("Dialog", "*x+"))
        self.expression_lineEdit_6_4.setText(_translate("Dialog", "1"))
        self.label_71.setText(_translate("Dialog", "*x+"))
        self.expression_lineEdit_7_4.setText(_translate("Dialog", "1"))
        self.groupBox_3.setTitle(_translate("Dialog", "Управление"))
        self.label_42.setText(_translate("Dialog", "Статус"))
        self.pushButton.setText(_translate("Dialog", "Вычислить"))
        self.pushButton_2.setText(_translate("Dialog", "График"))
        self.pushButton_3.setText(_translate("Dialog", "Диаграмма"))
        self.pushButton_4.setText(_translate("Dialog", "Возмущения"))
        self.groupBox.setTitle(_translate("Dialog", "Начальные значения переменных"))
        self.label_12.setText(_translate("Dialog", "длитлеьность реабилитационного приода"))
        self.label_14.setText(_translate("Dialog", "степень осложений заболевания"))
        self.label_10.setText(_translate("Dialog", "длительность инкубационного периода"))
        self.label.setText(_translate("Dialog", "летальность"))
        self.label_13.setText(_translate("Dialog", "устойчивость вируса к лекарствам"))
        self.label_2.setText(_translate("Dialog", "численность инфицированных"))
        self.label_9.setText(_translate("Dialog", "уровень развития медицины"))
        self.label_4.setText(_translate("Dialog", "численность госпитализированных"))
        self.label_8.setText(_translate("Dialog", "тяжесть симптомов"))
        self.label_52.setText(_translate("Dialog", "количество умерших от заболевания"))
        self.label_5.setText(_translate("Dialog", "изолированность"))
        self.label_3.setText(_translate("Dialog", "численность населения"))
        self.label_6.setText(_translate("Dialog", "скорость распроспространения"))
        self.label_7.setText(_translate("Dialog", "досутпность лекарств"))
        self.label_11.setText(_translate("Dialog", "длительность периода полного развития болезни"))
        self.begin_expression_lineEdit_15.setText(_translate("Dialog", "0.67"))
        self.begin_expression_lineEdit_11.setText(_translate("Dialog", "0.52"))
        self.begin_expression_lineEdit_14.setText(_translate("Dialog", "0.7534"))
        self.begin_expression_lineEdit_12.setText(_translate("Dialog", "0.25"))
        self.begin_expression_lineEdit_13.setText(_translate("Dialog", "0.678"))
        self.begin_expression_lineEdit_7.setText(_translate("Dialog", "0.9"))
        self.begin_expression_lineEdit_10.setText(_translate("Dialog", "0.234"))
        self.begin_expression_lineEdit_9.setText(_translate("Dialog", "0.567"))
        self.begin_expression_lineEdit_8.setText(_translate("Dialog", "0.24"))
        self.begin_expression_lineEdit_6.setText(_translate("Dialog", "0.4"))
        self.begin_expression_lineEdit_3.setText(_translate("Dialog", "0.6"))
        self.begin_expression_lineEdit_5.setText(_translate("Dialog", "0.7"))
        self.begin_expression_lineEdit_4.setText(_translate("Dialog", "0.5"))
        self.begin_expression_lineEdit_2.setText(_translate("Dialog", "0.9"))
        self.begin_expression_lineEdit_1.setText(_translate("Dialog", "0.9"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Параметры"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Графики"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Диаграмма"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Возмущение"))

    def addItems(self):
        self.comboBox_1.clear()
        self.comboBox_2.clear()
        self.comboBox_3.clear()
        self.comboBox_4.clear()
        self.comboBox_5.clear()
        self.comboBox_6.clear()
        self.comboBox_7.clear()
        for i in range(1, 127):
            self.comboBox_1.addItem(str(i))
            self.comboBox_2.addItem(str(i))
            self.comboBox_3.addItem(str(i))
            self.comboBox_4.addItem(str(i))
            self.comboBox_5.addItem(str(i))
            self.comboBox_6.addItem(str(i))
            self.comboBox_7.addItem(str(i))
